### ISSUE TITLE
unsigned script

### ISSUE THREAD

**Issue by joey102** [fenneh/bfa-addon-butler#1]
Hello,

Because the script is unsigned when executing it an error flashes by before the prompt closes unless the correct execution policy has been set.  

```
PS D:\Games\Blizzard\World of Warcraft Beta\bfa-addon-butler-master> .\Get-WoWAlphaAddons.ps1
.\Get-WoWAlphaAddons.ps1 : File D:\Games\Blizzard\World of Warcraft
Beta\bfa-addon-butler-master\Get-WoWAlphaAddons.ps1 cannot be loaded. The file D:\Games\Blizzard\World of Warcraft
Beta\bfa-addon-butler-master\Get-WoWAlphaAddons.ps1 is not digitally signed. You cannot run this script on the current
system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\Get-WoWAlphaAddons.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

Moving into an Unrestricted prompt resolves the issue; `powershell.exe -ExecutionPolicy Unrestricted`

Perhaps add a line that catches the error and explains what to do when the script stops.

**Comment by fenneh** [comment]
Thanks for the report, will fix up the docs when I get home.

**Comment by fenneh** [comment]
Should be fixed, included a batch file which will launch a unrestricted powershell prompt.
